DROP PROCEDURE IF EXISTS API_InsertNewApplication;
CREATE PROCEDURE API_InsertNewApplication(IN entity VARCHAR(255))
 BEGIN
  DECLARE GEUUID VARCHAR(255);
  DECLARE APPUUID VARCHAR(255);
  DECLARE EFUNCUUID VARCHAR(255);
  SELECT UUID() INTO GEUUID;
  SELECT UUID() INTO APPUUID;
  SELECT id FROM function WHERE `desc`="Student" INTO EFUNCUUID;
  INSERT INTO groupentity VALUES (GEUUID,entity,EFUNCUUID,
                                  NULL,NOW(),entity,NULL,NULL);
  INSERT INTO application VALUES (APPUUID,entity,NOW());
  INSERT INTO applicationgroup VALUES (APPUUID,GEUUID,NOW(),entity);
  SELECT APPUUID, GEUUID;
 END;