DROP PROCEDURE IF EXISTS API_InsertNewApplication;
CREATE PROCEDURE API_InsertNewApplication(IN entity VARCHAR(255))
 BEGIN
  DECLARE GEUUID VARCHAR(255);
  DECLARE APPUUID VARCHAR(255);
  DECLARE EFUNCUUID VARCHAR(255);
  SELECT UUID() INTO GEUUID;
  SELECT UUID() INTO APPUUID;
  SELECT id FROM function WHERE `desc`="Student" INTO EFUNCUUID;
  INSERT INTO groupentity (id,entity,function,createdin,createdby) VALUES (GEUUID,entity,EFUNCUUID,NOW(),entity);
  INSERT INTO application VALUES (APPUUID,entity,NOW());
  INSERT INTO applicationgroup VALUES (APPUUID,GEUUID,NOW(),entity);
  SELECT APPUUID, GEUUID;
 END;

DROP PROCEDURE IF EXISTS API_IsTeacher;
CREATE PROCEDURE API_IsTeacher(IN entity VARCHAR(255))
BEGIN
  DECLARE TEACHER BOOLEAN;
  SELECT EXISTS(SELECT * FROM teacher AS t where t.id=entity) INTO TEACHER;
  SELECT TEACHER;
END;
